# workflow do testowania end-to-end z użyciem Playwright uruchamianego na każdym pushu i pull requestcie. 
# Testy są wykonywane na różnych warstwach aplikacji

name: CI - Playwright Cross-Layer Testing

# sekcja, która definiuje, kiedy workflow ma być uruchamiany.

on:
 push:
 pull_request:

# sekcja definiująca zadania do wykonania w ramach workflow.
jobs:
# zadanie testowe:
  test:
# runs-on -  sekcja, która definiuje, na jakim systemie (OS) ma być uruchamiane zadanie. 
    runs-on: ubuntu-latest

  steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'